---
apiVersion: v1
kind: ConfigMap
metadata:
  name: guardian-config
  namespace: chainbridge-guardian
data:
  config.json: |+
    {
      "ingestors": {
          "bridgeTransferPaths": [
              {
                  "destination": 1,
                  "origin": 0
              }
          ],
          "dataSources": {
              "depositRecords": [
                  {
                      "endpoint": "https://graphs-api.phala.network/subgraphs/name/chainbridge",
                      "type": "subgraph"
                  }
              ],
              "proposals": [
                  {},
                  {
                      "endpoint": "https://subquery-api.phala.network/",
                      "type": "subquery"
                  }
              ],
              "substrates": {
                  "1": {
                      "chainBridge": true,
                      "endpoint": "wss://khala-api.phala.network/ws/"
                  }
              }
          }
      }
    }
  ormconfig.json: |+
    {
        "type": "postgres",
        "host": "postgres",
        "port": 5432,
        "username": "guardian",
        "password": "guardian",
        "database": "guardian",
        "logging": false,
        "synchronize": true
    }

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: chainbridge-guardian
data:
  alerts.yml: |+
    groups:
      - name: guardian
        rules:
          - alert: GuardianDown
            expr: up == 0
            for: 5m
            annotations:
              summary: Guardian instance is inaccessible
          - alert: FailedProposals
            expr: chainbridge_proposal_counts{status="approved"} > 0
            for: 30m
            annotations:
              summary: Some proposals are failed
          - alert: NotFinalizedProposals
            expr: chainbridge_proposal_counts{status="undefined"} > 0
            for: 30m
            annotations:
              summary: Some proposals are never finalized
          - alert: ImbalanceBridgeAccount
            expr: (266000000 - (sum(chainbridge_account_balances) + sum(chainbridge_deposit_balances) / 1000000000000)) > 1000
            for: 30m
            annotations:
              summary: Some deposits are gone
  prometheus.yml: |+
    global:
      scrape_interval: 5s
      evaluation_interval: 90s

    rule_files:
      - "alerts.yml"

    scrape_configs:
      - job_name: guardian_metrics
        static_configs:
          - targets: ["guardian:3000"]
