groups:
  - name: guardian
    rules:
      - alert: GuardianDown
        expr: up == 0
        for: 5m
        annotations:
          summary: Guardian instance is inaccessible
      - alert: FailedProposals
        expr: chainbridge_proposal_counts{status="approved"} > 0
        for: 5m
        annotations:
          summary: Some proposals are failed
      - alert: NotFinalizedProposals
        expr: chainbridge_proposal_counts{status="undefined"} > 0
        for: 5m
        annotations:
          summary: Some proposals are never finalized
